name: Jueun Hwang
favicon: null
layout_spectrum: 0.49229
typography_spectrum: 0.09827
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#f12b24'
    - '#74899e'
    - '#413df6'
  brandStrength: 0.6875
  lightness: 0.0625
  saturation: 0.875
  rhythmicContrast: 0.6699601439759135
purpose: []
