name: Jueun Hwang
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6079
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: '[Jueun Hwang]'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#BF7601'
    - '#372115'
    - '#E0E0E0'
    - '#FFB554'
    - '#C69142'
  brandStrength: 0.2473118
  lightness: 0.4086021
  saturation: 0.4318996
  rhythmicContrast: 0.1308244
purpose: []
