name: Jueun Hwang
favicon: null
layout_spectrum: 0.49229
typography_spectrum: 0.11368
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d21e4f'
    - '#cacac9'
    - '#fdfdfd'
    - '#bc6e40'
  brandStrength: 0.625
  lightness: 0.5614330398384482
  saturation: 0.875
  rhythmicContrast: 0.6699601439759135
purpose: []
