name: Jueun Hwang
favicon: null
layout_spectrum: 0.74373
typography_spectrum: 0.6079
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Jueun Hwang
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010300'
    - '#53fefb'
    - '#8b8a6f'
    - '#fcfbe5'
    - '#e5b4db'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.4318996
  rhythmicContrast: 1
purpose: []
